# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(default='')),
                ('subject', models.TextField(default='')),
                ('start', models.DateField(default='')),
                ('end', models.DateField(default='')),
            ],
        ),
    ]
