# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20200823_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='WE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(default='')),
                ('jobTitle', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
