# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_we'),
    ]

    operations = [
        migrations.RenameField(
            model_name='we',
            old_name='jobTitle',
            new_name='job',
        ),
    ]
